apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ysoynasrd-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ysoynasrd-dotnet-basic-gitops